# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 023a2e1431b3b30307e234de7c902a8718f304484a4e0d73a29ea29432d6b12adfa63e352704476df7a75dfed93e0a4095512871d88d9f53dc159f83e8834ab5
  aws_access_key_id: AKIAVKJUUET2JAIAJDV4
  aws_secret_access_key: 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
  aws_region: eu-west-1
  s3_region: eu-west-1
  aws_bucket: rekon-rafael

test:
  secret_key_base: c206bc787cdc16167b2a140b6d7bf7fc31c61ae2b50ca3f3bfab24c1f381e6d7acc4c5324cfce76df8ab9cc55492a1d885b28c1c8404868f5c53542ec63a75ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
